### ISSUE TITLE
TreeType Error

### ISSUE THREAD

**Issue by jbbrunsveld** [Yavin/symfony-form-tree#2]
Got this error after updating:

Catchable fatal error: Argument 1 passed to Yavin\Symfony\Form\Type\TreeType::__construct() must implement interface Symfony\Component\PropertyAccess\PropertyAccessorInterface, array given, called in /var/www/jifeline/app/cache/dev/appDevDebugProjectContainer.php on line 12559 and defined in /my/www/vendor/yavin/symfony-form-tree/src/Yavin/Symfony/Form/Type/TreeType.php on line 22

It's definitely  a BC break. I got this error on production but not on my local environment. After updating to the latest commit got error in this env. too. I strongly suggest to tag a refactored version.
For now a quickfix in my composer.json : "yavin/symfony-form-tree": "dev-master#71545fb792", solved the problem.

**Comment by Yavin** [comment]
closing as it was answered
